version: 0.2

phases:
  install:
    commands:
      - echo "[+] Scanning for security vulnerability within dependencies"
  pre_build:
    commands:
      - yum install python-pip
     
  build:
    commands:
      - aws cloudformation package --template-file /mycicdproject/template.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file newStageTemplate.yaml
  post_build:
    commands:
      - echo "SAM packaging completed on `date`"

artifacts:
  files:
    - newStageTemplate.yaml
  discard-paths: yes
