apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
        env: {{ .Values.env }}
    spec:
      serviceAccountName: node-app-sa
      containers:
        - name: node-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3000
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_ENV
              value: {{ .Values.env }}
            - name: DD_SERVICE
              value: node-app